Q1: values added: 20
Q2: final result: 20
Q3: values added: 20
Q4: returns an error, because with the let keyword, the variable result can only be accessed within the block of the function and is not defined outside the block. Calling it outside the function sumValues causes a ReferenceError.
Q5: returns an error, because with the const keyword, the variable result cannot be reassigned. Line 7 of the code trying to reassign result causes a TypeError.
Q6: returns an error. The TypeError is returned before line 13.
